### ISSUE TITLE
Compiling the `distance` library gives deprecation warning on Elixir >= 1.16

### ISSUE THREAD

**Issue by cgrothaus** [pkinney/distance#7]
Compiling the `distance` library gives deprecation warning on Elixir >= 1.16:
```
warning: pattern matching on 0.0 is equivalent to matching only on +0.0 from Erlang/OTP 27+. Instead you must match on +0.0 or -0.0
└─ lib/distance/vincenty.ex: Distance.Vincenty.calculate_cos2_sigma_m/4
```

**Comment by woolfred** [comment]
FYI: @cgrothaus and I had a look at this yesterday evening, but hadn't the time to create a PR yet. Coming soon ™️

**Comment by pkinney** [comment]
Fixed in 1.1.2: https://github.com/pkinney/distance/pull/8

**Comment by cgrothaus** [comment]
Thank you! It seems @woolfred and me were too slow with the promised PR 🐌 😀 .

**Comment by pkinney** [comment]
No worries! I needed to update the CI environment and some of the dependencies anyway.

Thank you for the issue!!
